version: "3.8"

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - job-portal-net
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mongosh", "localhost:27017", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      retries: 5
      start_period: 10s    
  

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "8000:8000"
    networks:
      - job-portal-net
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      - ./backend/.env
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:8000/health || exit 1"]
      interval: 30s
      retries: 5
      start_period: 20s

        

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "5173:5173"
    networks:
      - job-portal-net
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    

networks:
  job-portal-net:
    driver: bridge

volumes:
  mongodb_data:
    




