apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mern-manager-binding
  namespace: sahil-namespace
subjects:
- kind: User
  name: mern-user 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: mern-manager
  apiGroup: rbac.authorization.k8s.io
