apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: sahil-namespace
  name: mern-manager
rules:
- apiGroups: ["", "apps", "extensions", "autoscaling"]
  resources: ["services", "pods" , "horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
