apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: mern-vpa
  namespace: sahil-namespace
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-deployment
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: backend-container
        minAllowed:
          cpu: 50m         # 128Mi memory
          memory: 128Mi
        maxAllowed:
          cpu: 500m        # 1Gi memory     
          memory: 1Gi

